# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               m1kemu-sec
tagline:             'A Security-focused blog about things'
description:         'A Security-focused blog about things'
url:                 https://m1kemu.github.io
baseurl:             'https://m1kemu.github.io'
paginate:            5

# About/contact
author:
  name:              Mike Music
  url:               https://twitter.com/m1kemu
  email:             localhost@localhost.com

# Custom vars
version:             0.0.1
