# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               m1kemu-sec
tagline:             'My mostly security-focused thoughts, projects, and rants'
description:         'My mostly security-focused thoughts, projects, and rants'
url:                 https://m1kemu.github.io
baseurl:             'https://m1kemu.github.io'
paginate:            1

# About/contact
author:
  name:              Mike Music
  url:               https://twitter.com/m1kemu

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate, jekyll-feed]
